version: '3'
services:
  api:
    image: node:8.1.2-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: sh -c "/opt/app/entrypoint.sh install --force && /opt/app/entrypoint.sh build"
  frontend:
    image: node:8.1.2-alpine
    volumes:
      - ./frontend:/opt/app
    entrypoint: sh -c "/opt/app/entrypoint.sh install --force && /opt/app/entrypoint.sh build"
