version: '3'
services:
  web:
    image: nginx:1.13.1-alpine
    links:
     - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node:8.1.2-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
  frontend:
    image: node:8.1.2-alpine
    volumes:
      - ./frontend:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
