version: '3'
services:
  web:
    image: asermax/catering-colectivo-web:latest
    build: .
  api:
    image: asermax/catering-colectivo-api:latest
    build: api/
    volumes:
      - ./api/node_modules:/opt/app/node_modules
