version: '3'
services:
  web:
    image: catering-colectivo/web:latest
    build: .
  api:
    image: catering-colectivo/api:latest
    build: api/
    volumes:
      - ./api/node_modules:/opt/app/node_modules
