version: '3'
services:
  api:
    image: node:8.1.2-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: build
  frontend:
    image: node:8.1.2-alpine
    volumes:
      - ./frontend:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: build
