version: '3'
services:
  web:
    image: nginx:1.12-alpine
    links:
     - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: mhart/alpine-node:8
    volumes:
      - ./api:/opt/app
    command: sh -c "cd /opt/app && yarn start"
  frontend:
    image: mhart/alpine-node:8
    volumes:
      - ./frontend:/opt/app
    command: sh -c "cd /opt/app && yarn start"
